//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PollyApp.EFModel
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;

    public partial class CodeSet
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CodeSet()
        {
            this.ProjectAccessVoters = new HashSet<ProjectAccessVoter>();
        }
    
        public int Id { get; set; }
        public string CodeText { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
         
        public virtual ICollection<ProjectAccessVoter> ProjectAccessVoters { get; set; }
    }
}
