//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PollyApp.EFModel
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;

    public partial class ProjectAccessVoter
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ProjectAccessVoter()
        {
            this.Results = new HashSet<Result>();
        }
    
        public int Id { get; set; }
        public Nullable<bool> IsUsed { get; set; }
        public Nullable<int> CodeSetId { get; set; }
        public Nullable<int> UserSetId { get; set; }
        public int ProjectId { get; set; }

         
        public virtual CodeSet CodeSet { get; set; }
         
        public virtual Project Project { get; set; }
         
        public virtual UserSet UserSet { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
         
        public virtual ICollection<Result> Results { get; set; }
    }
}
