//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PollyApp.EFModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Project
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Project()
        {
            this.Questions = new HashSet<Question>();
            this.ProjectAccessVoters = new HashSet<ProjectAccessVoter>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<int> TypeId { get; set; }
        public bool IsActive { get; set; }
        public Nullable<int> ShareId { get; set; }
        public string UrlCode { get; set; }
        public Nullable<int> AccessId { get; set; }
        public Nullable<int> QuizConfId { get; set; }
        public string ProjectAccess { get; set; }
        public string ProjectLink { get; set; }
    
        public virtual PollAccess PollAccess { get; set; }
        public virtual PollShare PollShare { get; set; }
        public virtual PollType PollType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Question> Questions { get; set; }
        public virtual QuizConfigurator QuizConfigurator { get; set; }
        public virtual User User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProjectAccessVoter> ProjectAccessVoters { get; set; }
    }
}
