//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PollyApp.EFModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProjectAccessVoter
    {
        public int Id { get; set; }
        public Nullable<bool> IsUsed { get; set; }
        public Nullable<int> CodeSetId { get; set; }
        public Nullable<int> UserSetId { get; set; }
        public Nullable<int> ProjectId { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public Nullable<System.DateTime> VotedOn { get; set; }
    
        public virtual CodeSet CodeSet { get; set; }
        public virtual Project Project { get; set; }
        public virtual UserSet UserSet { get; set; }
    }
}
